### ISSUE TITLE
Sluggish moving trough game when slow CPU or heavy CPU load and complex configuration

### ISSUE THREAD

**Issue by Aloril** [TCEC-Chess/tcecgui#210]
When using complex non-minimal preset and using left/right keys to move trough game, board update is sluggish with slow CPU speed.

**Comment by snicolet** [comment]
I have found that it helps a lot to click the crosses to close the animated ads by Google, and same for the preview of the twitch live stream

**Comment by octopoulos** [comment]
There's already a +80% speed improvement since 5 days ago, can see it in options => extra => benchmark.
Now, considering 90% of the time is spent on the browser updating the layout, the DOM and painting the elements, there doesn't seem to be any way to improve the speed any more except from helping the browser create/destroy fewer nodes, which will be the next objective. I guess we might see another +50% or +100% speed improvement soon.

**Comment by Aloril** [comment]
PR226 improves speed further, quite snappy now even with CPU load.
