### ISSUE TITLE
Eval graph scale poor when missing data

### ISSUE THREAD

**Issue by nickolasreynolds** [TCEC-Chess/tcecgui#76]
Refer to the following image: https://i.imgur.com/k0s2L9C.png

The eval graph horizontal scale should never be larger than the last move of the game. Missing one of the kibitzers also sometimes affects the vertical scale (which also shouldn't happen), but that generally still leaves the eval graph readable and usable.

**Comment by octopoulos** [comment]
"The eval graph horizontal scale should never be larger than the last move of the game." ... that's actually incorrect, the kibitzer shows the eval of the next move, so the horizontal scale must be larger than the last move. Also you make it sound like it's easy, but it's not, because of asynchronicity: the last move might not have been received, for example if the computer goes to sleep then resumes 30 minutes later, probably a few moves have already been played, right? And kibitzers are still sending information, we can't just ignore it because they're after the last move.
I think the current solution is pretty effective, this effect that your screenshot shows will not last long.
